message("Converting phased_SNPs.vcf to InputVariantsforphasing")
library("vcfR")
phased_VCF <- read.vcfR("phased_SNPs.vcf")
var1 <- sapply(strsplit(sapply(strsplit(phased_VCF@gt[,2],":"), "[", 1),"|"), "[", 1)
var2 <- sapply(strsplit(sapply(strsplit(phased_VCF@gt[,2],":"), "[", 1),"|"), "[", 3)
InputVariants <- as.data.frame(cbind(phased_VCF@fix[, c(1:2, 4, 5)], var1, var2))
InputVariants$CHROM <- as.character(InputVariants$CHROM)
InputVariants$POS <- as.numeric(as.character(InputVariants$POS))
InputVariants$REF <- as.character(InputVariants$REF)
InputVariants$ALT <- as.character(InputVariants$ALT)
InputVariants$var1 <- as.numeric(as.character(InputVariants$var1))
InputVariants$var2 <- as.numeric(as.character(InputVariants$var2))
write.table(InputVariants, "InputVariants_forphasing.txt", sep = "\t", row.names = F, col.names = F, quote = F, na = "")